### PR TITLE
Ensure multi-arch images are copied

### PR DESCRIPTION
**Pull request by alexandermarston**
Adding an additional argument `--multi-arch all` to ensure that all arch images are copied.

```
      --multi-arch string                     How to handle multi-architecture images (system, all, or index-only)
```

### CODE REVIEW

**Review by estahn — APPROVED** [review]

**Comment by alexandermarston** [comment]
Thanks @estahn when can we expect a new release?

**Comment by estahn** [comment]
@alexandermarston I can cust a release today, just waiting for #425

**Comment by kjvellajr** [comment]
I think this caused a regression. When skopeo is invoked I see the following trace logs:

```
... level=fatal msg=\"Cannot use --all and --multi-arch flags together\"\n"
```

https://github.com/estahn/k8s-image-swapper/blob/main/pkg/webhook/image_swapper.go#L372

**Comment by alexandermarston** [comment]
> I think this caused a regression. When skopeo is invoked I see the following trace logs:
> 
> ```
> ... level=fatal msg=\"Cannot use --all and --multi-arch flags together\"\n"
> ```
> 
> https://github.com/estahn/k8s-image-swapper/blob/main/pkg/webhook/image_swapper.go#L372

#445 raised to remove --all args.

**Pull request merged**
