### PR TITLE
Fix docker references with both tag and digest

### LINKED ISSUE #15: Refactor logging to use trace instead of debug
Some logging is too verbose and should go to tracing.

### LINKED ISSUE #48: Docker references with both a tag and digest are currently not supported
Hi,
Receiving the titled error when using image that includes tags and digest like `k8s.gcr.io/ingress-nginx/controller:v0.43.0@sha256:9bba603b99bf25f6d117cf1235b6598c16033ad027b143c90fa5b3cc583c5713`

Where this limitation is coming from? can't ECR support digest?
Can we somehow overcome that so the tool will support that?

### PR DESCRIPTION
**Pull request by rattboi**
fix #48

This solution is taken almost directly from CRI-O, as referenced here: https://github.com/cri-o/cri-o/pull/3060/files

### CODE REVIEW

**Comment by bradonkanyid** [comment]
@estahn any way to get eyes on this? I *think* it's pretty straightforward.

**Comment by bradonkanyid** [comment]
@estahn sorry to ping again, but it's been almost a month. Am I missing something or just your availability?

**Comment by estahn** [comment]
> @estahn sorry to ping again, but it's been almost a month. Am I missing something or just your availability?

Apologies, I just started a new role and have been relatively busy. It's testing now.

**Comment by bradonkanyid** [comment]
Seems like the non-codecov ones are not related to my code. Not sure what the deal is with image scan, pre-commit, and linting failing.

**Comment by bradonkanyid** [comment]
@estahn these failures seem unrelated to my code. Can I get some guidance on what it'd take to get this merged?

**Comment by estahn** [comment]
> @estahn these failures seem unrelated to my code. Can I get some guidance on what it'd take to get this merged?

You're correct. I updated `golangci-lint` which solved it, but the image security scan fails. I can reproduce it locally atm but trying to get it resolved today.

See:
https://github.com/estahn/k8s-image-swapper/runs/7159973224?check_suite_focus=true

**Pull request merged**
